vich_uploader:
    db_driver: orm

    mappings:
        demandes:
            uri_prefix: /files/demandes
            upload_destination: '%kernel.project_dir%/stockage/fichiers/demandes'
#            upload_destination: '192.168.1.6/Backups/Storage/Files'
#           upload_destination: '%kernel.project_dir%/public%app.path.documents%'
            namer: Vich\UploaderBundle\Naming\SlugNamer
            
            inject_on_load: true
            delete_on_update: false
            delete_on_remove: true

        